name: Real Estate CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: estate_backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build # Or remove if backend doesn't have build

      - name: Run Server (Optional)
        run: node index.js # Only for validation; remove in CI
